server.port=8888
spring.application.name=config-server

# Use native profile to read from local directory
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=${CONFIG_REPO_PATH:file:///c:/Users/abhiy/Downloads/eurakaservicedemo/finflow-loan-sprint1_full/finflow-loan-sprint1/config-repo}

# Eureka Config
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Eureka Instance Configuration
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.instance-id=${spring.application.name}:${server.port}
