server.port=8082
spring.application.name=application-service
spring.config.import=optional:configserver:http://localhost:8888/
# Swagger Config mapping
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/applications/v3/api-docs

# Database Config - using same MySQL instance but different schema
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/applicationdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345mysql}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
