server.port=8083
spring.application.name=document-service
spring.config.import=optional:configserver:http://localhost:8888/
# Swagger Config mapping
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/documents/v3/api-docs

# Database Config - using same MySQL instance but different schema
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/documentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345mysql}

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Max File Size Upload configs
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

