# Auth Service Config
server.port=8081

# Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DATABASE_HOST:localhost}:3306/authdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345mysql}

# JWT Config
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Swagger Config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/auth/v3/api-docs
