# Document Service Config
server.port=8083

# Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${DATABASE_HOST:localhost}:3306/documentdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:12345mysql}

# Max File Size Upload configs
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger Config
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/documents/v3/api-docs
